"""YouTube download via yt-dlp.

Quality policy mirrors Tyrrrz/YoutubeDownloader.Core (Highest + Mp4 preference):
uncapped best video+audio by default, prefer mp4/m4a when available, ffmpeg merge.
"""
import json
import os
import re
from typing import Dict, Optional, Tuple
from urllib.parse import parse_qs, urlparse

from .config import DOWNLOAD_FORMAT, OUTPUT_DIR, YTDLP_COOKIES_FILE, YTDLP_COOKIES_FROM_BROWSER, _env

# Aliases matching YoutubeDownloader.Core VideoQualityPreference
_MAX_ALIASES = frozenset({"max", "highest", "best", "maxres"})
_LOW_ALIASES = frozenset({"lowest", "min", "worst"})
_MEDIA_EXTS = (".mp4", ".mkv", ".webm")

# A current desktop browser UA — helps requests look like a real viewer, not a bot.
_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)
# Clients whose combined formats are fed to yt-dlp at once. 'tv'/'mweb'/'web'
# expose the full ladder incl. 1440p/4K; 'ios'/'android' add 403-resistant
# fallbacks. yt-dlp aggregates all of them and picks the highest-quality format.
_DEFAULT_PLAYER_CLIENTS = ("tv", "mweb", "web", "ios", "web_safari", "android")


# Project root (parent of shorts_generator/)
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _json_cookies_to_netscape(cookies: list) -> str:
    """Convert Chrome/Cookie-Editor JSON export to Netscape cookies.txt for yt-dlp."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by ClipClipper from cookies.json",
    ]
    for c in cookies:
        if not isinstance(c, dict):
            continue
        domain = str(c.get("domain") or "").strip()
        name = str(c.get("name") or "").strip()
        if not domain or not name:
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(c.get("path") or "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        if c.get("session") or not c.get("expirationDate"):
            expiration = 0
        else:
            expiration = int(float(c["expirationDate"]))
        value = str(c.get("value") or "")
        lines.append(
            f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


def _load_json_cookies(path: str) -> list:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and isinstance(data.get("cookies"), list):
        return data["cookies"]
    raise ValueError(f"unsupported cookie JSON shape in {path}")


def _ensure_netscape_cookiefile(path: str) -> str:
    """Return a Netscape cookies.txt path (converting .json on the fly)."""
    if not path.lower().endswith(".json"):
        return path
    cache = os.path.join(OUTPUT_DIR, ".cookies_netscape.txt")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    src_mtime = os.path.getmtime(path)
    if not os.path.isfile(cache) or os.path.getmtime(cache) < src_mtime:
        netscape = _json_cookies_to_netscape(_load_json_cookies(path))
        with open(cache, "w", encoding="utf-8") as f:
            f.write(netscape)
    return cache


def _resolve_cookie_file() -> str:
    """Find cookies file: env path → project cookies.json / cookies.txt."""
    env = (os.getenv("YTDLP_COOKIES_FILE") or YTDLP_COOKIES_FILE).strip()
    candidates = []
    if env:
        candidates.append(env)
        if not os.path.isabs(env):
            candidates.append(os.path.join(_PROJECT_ROOT, env))
    else:
        candidates.extend(
            os.path.join(_PROJECT_ROOT, name) for name in ("cookies.json", "cookies.txt")
        )
    for path in candidates:
        if path and os.path.isfile(path):
            return _ensure_netscape_cookiefile(os.path.abspath(path))
    return ""


def _auth_opts(use_cookies: bool = True) -> Dict:
    """Cookie options for yt-dlp. File cookies take priority over browser."""
    opts: Dict = {}
    if not use_cookies:
        return opts
    cookiefile = _resolve_cookie_file()
    if cookiefile:
        opts["cookiefile"] = cookiefile
        return opts
    browser = (os.getenv("YTDLP_COOKIES_FROM_BROWSER") or YTDLP_COOKIES_FROM_BROWSER).strip()
    if browser and browser.lower() not in ("none", "false", "off", "0"):
        opts["cookiesfrombrowser"] = tuple(p.strip() or None for p in browser.split(":"))
    return opts


def _cookies_source_label() -> str:
    cookiefile = _resolve_cookie_file()
    if cookiefile:
        # Show the original json/txt name, not the converted cache path
        env = (os.getenv("YTDLP_COOKIES_FILE") or YTDLP_COOKIES_FILE).strip()
        if env:
            return env
        for name in ("cookies.json", "cookies.txt"):
            if os.path.isfile(os.path.join(_PROJECT_ROOT, name)):
                return name
        return os.path.basename(cookiefile)
    browser = (os.getenv("YTDLP_COOKIES_FROM_BROWSER") or YTDLP_COOKIES_FROM_BROWSER).strip()
    return browser.split(":")[0] if browser else ""


def _cookies_browser_label() -> str:
    """Backward-compat alias — returns browser name only when no cookie file."""
    if _resolve_cookie_file():
        return ""
    browser = (os.getenv("YTDLP_COOKIES_FROM_BROWSER") or YTDLP_COOKIES_FROM_BROWSER).strip()
    return browser.split(":")[0] if browser else ""


def _player_clients() -> list:
    raw = _env("YTDLP_PLAYER_CLIENTS")
    if raw:
        return [c.strip() for c in raw.split(",") if c.strip()]
    return list(_DEFAULT_PLAYER_CLIENTS)


def _base_opts(out_dir: str, fmt: str, tag: str, *, use_cookies: bool = True) -> Dict:
    """Shared yt-dlp options that make us look authentic + resilient."""
    opts: Dict = {
        "format": _format_for(fmt),
        "outtmpl": os.path.join(out_dir, f"source_%(id)s_{tag}.%(ext)s"),
        "merge_output_format": "mp4",
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "http_headers": {"User-Agent": _USER_AGENT},
        "retries": 10,
        "fragment_retries": 10,
        "extractor_retries": 3,
        "socket_timeout": 30,
    }
    opts.update(_auth_opts(use_cookies=use_cookies))
    return opts


def _is_cookie_error(exc: Exception) -> bool:
    msg = str(exc).lower()
    needles = (
        "cookie",
        "could not copy",
        "failed to decrypt",
        "dpapi",
        "keyring",
        "no such browser",
        "profile",
    )
    return any(n in msg for n in needles)


def _attempt_download(
    yt_dlp,
    video_url: str,
    base_opts: Dict,
    clients: list,
) -> Tuple[Optional[Dict], Optional[str], Optional[Exception]]:
    """Try client sets until one succeeds. Returns (info, path, last_error)."""
    attempts: list = [clients] + [[c] for c in clients]
    last_err: Optional[Exception] = None
    for client_set in attempts:
        ydl_opts = dict(base_opts)
        ydl_opts["extractor_args"] = {"youtube": {"player_client": list(client_set)}}
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(video_url, download=True)
                path = ydl.prepare_filename(info)
                if not os.path.exists(path):
                    stem, _ = os.path.splitext(path)
                    for ext in _MEDIA_EXTS:
                        if os.path.exists(stem + ext):
                            path = stem + ext
                            break
            return info, path, None
        except Exception as exc:  # noqa: BLE001
            last_err = exc
            if _is_cookie_error(exc):
                return None, None, exc
            label_set = "+".join(client_set)
            print(f"[download] clients '{label_set}' failed ({exc}); trying next…", flush=True)
    return None, None, last_err


def _import_ytdlp():
    try:
        import yt_dlp  # type: ignore
    except ImportError as e:
        raise RuntimeError(
            "yt-dlp is required. Install it with:\n    pip install -r requirements.txt"
        ) from e
    return yt_dlp


def _normalize_fmt(fmt: str) -> str:
    return (fmt or "max").strip().lower()


def _format_for(fmt: str) -> str:
    """Build a yt-dlp format selector from a quality preference.

    Mirrors YoutubeDownloader's TryGetBestOption:
      Highest  → best video+audio (prefer mp4/m4a, else any codec)
      UpToNp   → same with height<=N
      Lowest   → worst paired streams
    """
    key = _normalize_fmt(fmt)

    if key in _MAX_ALIASES:
        # Resolution first, container second. YouTube only ships mp4/H.264 up to
        # 1080p — 1440p/4K exist only as VP9/AV1 (webm), so an mp4-first selector
        # silently caps at 1080p. We merge to mp4 afterwards regardless.
        return "bestvideo*+bestaudio/best"

    if key in _LOW_ALIASES:
        return "worstvideo+worstaudio/worst"

    try:
        height = int(key)
    except ValueError:
        height = 1080

    # UpTo{height}p — resolution first, then any progressive fallback.
    return (
        f"bestvideo[height<={height}]+bestaudio/"
        f"best[height<={height}]/best"
    )


def extract_youtube_video_id(source: str) -> Optional[str]:
    parsed = urlparse(source)
    host = (parsed.netloc or "").lower()
    if host.startswith("www."):
        host = host[4:]

    if host in ("youtu.be",):
        video_id = parsed.path.lstrip("/").split("/", 1)[0]
        return video_id or None

    if "youtube.com" in host:
        if parsed.path.startswith("/watch"):
            qs = parse_qs(parsed.query)
            video_id = qs.get("v", [""])[0]
            return video_id or None
        match = re.search(r"/(?:shorts|embed|live)/([^/?#&]+)", parsed.path)
        if match:
            return match.group(1)

    return None


def require_youtube_url(source: str) -> str:
    video_id = extract_youtube_video_id(source)
    if not video_id:
        raise RuntimeError(
            f"YouTube URL required (got {source!r}). "
            "Local files and non-YouTube URLs are not supported."
        )
    return video_id


def _fmt_tag(fmt: str) -> str:
    key = _normalize_fmt(fmt)
    if key in _MAX_ALIASES:
        return "max"
    if key in _LOW_ALIASES:
        return "low"
    try:
        return str(int(key))
    except ValueError:
        return "max"


def _meta_path(source_path: str) -> str:
    stem, _ = os.path.splitext(source_path)
    return stem + ".meta.json"


def _save_meta(source_path: str, info: Dict) -> None:
    meta = {
        "id": info.get("id"),
        "title": info.get("title"),
        "duration": info.get("duration"),
        # Ranking signals (see UPLIFT_PLAN.md) — None on low-view videos
        "heatmap": info.get("heatmap"),
        "chapters": info.get("chapters"),
        "_has_signals": True,  # sentinel: distinguishes "probed, none" from old cache
    }
    with open(_meta_path(source_path), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)


def _probe_info(video_url: str, video_id: str) -> Dict:
    """One lightweight metadata fetch (no download) for signals backfill."""
    yt_dlp = _import_ytdlp()
    opts = {
        "quiet": True,
        "no_warnings": True,
        "skip_download": True,
        "http_headers": {"User-Agent": _USER_AGENT},
    }
    opts.update(_auth_opts())
    with yt_dlp.YoutubeDL(opts) as ydl:
        try:
            return ydl.extract_info(video_url, download=False)
        except Exception:
            return {"id": video_id, "title": video_id, "duration": 0}


def _load_meta(source_path: str, video_id: str, video_url: Optional[str] = None) -> Dict:
    path = _meta_path(source_path)
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            meta = json.load(f)
        # Backfill signals for caches written before this feature
        if not meta.get("_has_signals") and video_url:
            info = _probe_info(video_url, video_id)
            meta["heatmap"] = info.get("heatmap")
            meta["chapters"] = info.get("chapters")
            meta["_has_signals"] = True
            meta.setdefault("duration", info.get("duration"))
            try:
                with open(path, "w", encoding="utf-8") as f:
                    json.dump(meta, f, indent=2)
            except OSError:
                pass
        if meta.get("id") or meta.get("title"):
            return meta
    return {"id": video_id, "title": video_id, "duration": 0}


def find_local_source(
    out_dir: str,
    video_id: str,
    fmt: Optional[str] = None,
) -> Optional[str]:
    """Return a local source file if already downloaded (retry-safe, no network)."""
    if not os.path.isdir(out_dir):
        return None

    if fmt is not None:
        hit = _existing_download(out_dir, video_id, fmt)
        if hit:
            return hit

    # Retry fallback: accept any cached source for this video id in the folder
    prefix = f"source_{video_id}"
    candidates = []
    for name in os.listdir(out_dir):
        lower = name.lower()
        if name.startswith(prefix) and any(lower.endswith(ext) for ext in _MEDIA_EXTS):
            candidates.append(os.path.join(out_dir, name))
    if not candidates:
        return None

    # Prefer exact format tag, then legacy untagged, then largest file
    if fmt is not None:
        tag = _fmt_tag(fmt)
        for path in candidates:
            if f"_{tag}." in os.path.basename(path):
                return path
    for path in candidates:
        base = os.path.basename(path)
        if base in {f"source_{video_id}{ext}" for ext in _MEDIA_EXTS}:
            return path
    return max(candidates, key=lambda p: os.path.getsize(p))


def is_downloaded(
    video_url: str,
    out_dir: Optional[str] = None,
    fmt: Optional[str] = None,
) -> bool:
    video_id = extract_youtube_video_id(video_url)
    if not video_id:
        return False
    out_dir = out_dir or OUTPUT_DIR
    return find_local_source(out_dir, video_id, fmt=fmt or DOWNLOAD_FORMAT) is not None


def _existing_download(out_dir: str, video_id: str, fmt: str) -> Optional[str]:
    """Return cached path for this video_id + quality tag (avoids reusing a lower res)."""
    tag = _fmt_tag(fmt)
    for ext in _MEDIA_EXTS:
        candidate = os.path.join(out_dir, f"source_{video_id}_{tag}{ext}")
        if os.path.exists(candidate):
            return candidate
    if tag == "max":
        for ext in _MEDIA_EXTS:
            legacy = os.path.join(out_dir, f"source_{video_id}{ext}")
            if os.path.exists(legacy):
                return legacy
    return None


def download_youtube(
    video_url: str,
    fmt: Optional[str] = None,
    out_dir: Optional[str] = None,
) -> Tuple[str, Dict]:
    """Download a YouTube URL at the requested quality. Returns (local_path, info_dict)."""
    yt_dlp = _import_ytdlp()
    video_id = require_youtube_url(video_url)
    fmt = _normalize_fmt(fmt or DOWNLOAD_FORMAT)
    out_dir = out_dir or OUTPUT_DIR
    os.makedirs(out_dir, exist_ok=True)
    tag = _fmt_tag(fmt)

    cached = find_local_source(out_dir, video_id, fmt=fmt)
    if cached:
        print(f"[download] already on disk, skipping download: {cached}", flush=True)
        info = _load_meta(cached, video_id, video_url=video_url)
        return cached, info

    label = "max" if tag == "max" else f"{tag}p"
    print(f"[download] {video_url} @ {label} → {out_dir}/", flush=True)

    clients = _player_clients()
    cookie_src = _cookies_source_label()
    use_cookies = bool(cookie_src)
    if cookie_src:
        if cookie_src in ("edge", "chrome", "firefox", "brave", "chromium", "opera", "safari", "vivaldi"):
            print(
                f"[download] using browser cookies ({cookie_src}) — close that browser first if this fails",
                flush=True,
            )
        else:
            print(f"[download] using cookies from {cookie_src}", flush=True)

    info = None
    path = None
    last_err: Optional[Exception] = None
    tried_without_cookies = False

    base_opts = _base_opts(out_dir, fmt, tag, use_cookies=use_cookies)
    info, path, last_err = _attempt_download(yt_dlp, video_url, base_opts, clients)

    if info is None and use_cookies and last_err and _is_cookie_error(last_err):
        src = _cookies_source_label()
        print(
            f"[download] could not load cookies from {src}.\n"
            f"  ({last_err})\n"
            f"[download] retrying without cookies (quality may be lower)…",
            flush=True,
        )
        tried_without_cookies = True
        base_opts = _base_opts(out_dir, fmt, tag, use_cookies=False)
        info, path, last_err = _attempt_download(yt_dlp, video_url, base_opts, clients)

    using_cookies = use_cookies and not tried_without_cookies

    if info is None or path is None:
        hint = ""
        if not using_cookies:
            hint = (
                "\nDownload blocked or cookies unavailable. Sign in to YouTube in your browser, "
                "close it, then retry. Set YTDLP_COOKIES_FROM_BROWSER=edge in .env (default on Windows)."
            )
        raise RuntimeError(f"download failed for {video_url}: {last_err}{hint}")

    _save_meta(path, info)
    height = info.get("height")
    fps = info.get("fps")
    res = f" {height}p{int(fps) if fps else ''}" if height else ""
    print(f"[download] ready:{res} {path}", flush=True)

    if tag == "max" and isinstance(height, int) and height < 1080:
        print(
            "[download] note: only low-res formats were available. For HD/4K ensure:\n"
            "  1) Deno is installed and on PATH (for yt-dlp's JS challenge solver)\n"
            "  2) You're signed in to YouTube in your browser (cookies are used by default)\n"
            "  3) Delete any old low-res cached file and re-run",
            flush=True,
        )
    return path, info
